### ISSUE TITLE
vi mode

### ISSUE THREAD

**Issue by MovingtoMars** [MovingtoMars/liner#6]
https://www.gnu.org/software/bash/manual/html_node/Readline-vi-Mode.html

Not sure how desired this feature is.

**Comment by iamcodemaker** [comment]
I suspect this will require more than just custom key mappings. Some behavior is different depending on if insert mode or command mode is active. I suppose this could be accounted for with different mappings for different modes.

**Comment by iamcodemaker** [comment]
I believe implementing this would require detection of Esc key presses. Opened ticki/termion#43.

**Comment by iamcodemaker** [comment]
Started some work on this here https://github.com/iamcodemaker/liner/tree/vi. Depends on ticki/termion#45. Going to be some time before it is finished.

**Comment by iamcodemaker** [comment]
So I'm not sure how to proceed with this. I am almost done with the implementation, and so far the diff is more than 3000 lines. What is the best way to get this merged? I could submit the whole thing at once, but that seems like too much to review at once. I could also submit bits and pieces a little at a time and merge into a staging branch or something. What's the best way to proceed here?

**Comment by iamcodemaker** [comment]
Just looked at the changes again, if you exclude tests, the diff comes in at about 1k lines. Still very large.

**Comment by MovingtoMars** [comment]
Wow, thanks for all that work! You can just submit a pull request and I'll get around to it sometime soon. IMO the changes are too connected to merge seperately.

**Comment by iamcodemaker** [comment]
Actually, I think I can split some of these changes out. There is a set of changes to abstract key handling out from the Editor object. I can submit that separately. Stand by.

**Comment by iamcodemaker** [comment]
#24 contains the first step here. It decouples key press handling from the Editor object.

**Comment by iamcodemaker** [comment]
I think my branch is in a good spot. Undo support needs to be improved. But I am going to spend some time refactoring it into incremental changes so that it can be reviewed in chunks. This will also have the benefit of erasing WIP designs, making me look smarter :smile:

There may also need to be some additional changes in the future. With the current design, state is not tracked between calls to `read_line()`. This makes vi mode unable to repeat the last editing command between calls to `read_line()`. Not terribly difficult to fix, but it will require some thought.

**Comment by iamcodemaker** [comment]
This can be closed now.

**Comment by MovingtoMars** [comment]
Thank you.
